name: Dragons
main: mc.dragons.core.Dragons
version: 1.0.0
author: DragonRider747
depend: [ProtocolLib]
loadbefore: [WorldEdit]
load: POSTWORLD
commands:
  channel:
    description: Set speaking and listening chat channels.
    aliases: [c, ch, chat]
  dragons:
    description: DRAGONS
  fastforwarddialogue:
    description: Fast-forward through active quest dialogue.
  feedback:
    description: Send feedback about the game.
  friend:
    description: Make friends!
    aliases: f
  help:
    description: Halp
    aliases: '?'
  ilostthelousystick:
  msg:
    description: Send a private message.
    aliases: [tell, t, m, pm, whisper, w]
  myquests:
    description: List your active quests.
  party:
    description: Create, join, and manage parties.
    aliases: p
    description: Log on to system console.
  reply:
    description: Reply to your last incoming message.
    aliases: [r, re]
  syslogon:
    description: Log on to the system console.
  bypassdeathcountdown:
    description: (TESTER) Skip the death countdown and respawn instantly.
  clear:
    description: (TESTER) Clear your inventory. This cannot be undone.
  testquest:
    description: (TESTER) Force-begin a quest.
  gamemode:
    description: (BUILDER) Set gamemode.
    aliases: gm
  gma:
    description: (BUILDER) Set gamemode to Adventure.
  gmc:
    description: (BUILDER+B) Set gamemode to Creative.
  gms:
    description: (BUILDER+B) Set gamemode to Survival.
  gotofloor:
    description: (BUILDER) Go to the specified floor, overriding level requirements.
  speed:
    description: (BUILDER) Change your ground or flight speed.
  ban:
    description: (MOD) Ban a player.
  chatspy:
    description: (MOD) View other players' private messages.
  godmode:
    description: (MOD) Toggle God Mode.
    aliases: god
  info:
    description: (MOD) View a player's information.
  kick:
    description: (MOD) Kick a player.
  mute:
    description: (MOD) Mute a player.
  shout:
    description: (MOD) Broadcast to the entire server.
    aliases: [broadcast, bc]
  unban:
    description: (MOD) Unban a player.
  unmute:
    description: (MOD) Unmute a player.
  unvanish:
    description: (MOD) Unvanish yourself.
    aliases: uv
  vanish:
    description: (MOD) Become invisible to non-staff players.
    aliases: v
  viewpunishments:
    description: (MOD) View a player's punishment history.
  addon:
    description: (GM) Manage add-ons.
  floor:
    description: (GM) Manage floors.
  item:
    description: (GM) Manage items.
    aliases: i
  npc:
    description: (GM) Manage NPCs.
  placeholder:
    description: (GM) Set text placeholders for longer dialogue, etc.
    aliases: ph
  quest:
    description: (GM) Manage quests.
    aliases: q
  region:
    description: (GM) Manage regions.
  relore:
    description: (GM) Change the lore of your held item.
  rename:
    description: (GM) Rename your held item.
  restat:
    description: (GM) Change the stats of your held item.
  updatestats:
    description: (GM) Update a player's stats.
  debug:
    description: (ADMIN) Oops! Something went wrong.
  experiment:
    description: (ADMIN) Access experimental features.
  lag:
    description: (ADMIN) View server lag statistics.
  loglevel:
    description: (ADMIN) Set console log level.
  rank:
    description: (ADMIN) Set a player's rank.
  reloadquests:
    description: (ADMIN) Reload all quests. 
  removepunishment:
    description: (ADMIN) Remove a punishment from a player's history.
  serveroptions:
    description: (ADMIN) Manage server settings.
  verifygameintegrity:
    description: (ADMIN) Verify integrity of active game environment.
