name: Dragons
main: mc.dragons.dragons.core.Dragons
version: 1.0.0
author: DragonRider747
depend: [ProtocolLib]
loadbefore: [WorldEdit]
api-version: 1.13
commands:
  dragons:
    description: DRAGONS
  party:
    description: Create, join, and manage parties.
    aliases: /p
  friend:
    description: Add, accept, and manage friends.
    aliases: /f
  item:
    description: (GM) Manage items.
  quest:
    description: (GM) Manage quests.
    aliases: /q
  npc:
    description: (GM) Manage NPCs.
  info:
    description: (GM) View a player's information.
  region:
    description: (GM) Manage regions.
  clear:
    description: Clear your inventory. This cannot be undone.
  rank:
    description: (GM) Set player rank.
  permissionlevel:
    description: (SYSOP) Set player permission level.